// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ElasticsearchTypeProvider")>]
[<assembly: AssemblyProductAttribute("ElasticsearchTypeProvider")>]
[<assembly: AssemblyDescriptionAttribute("Elasticsearch Type Provider")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ElasticsearchTypeProvider"
    let [<Literal>] AssemblyProduct = "ElasticsearchTypeProvider"
    let [<Literal>] AssemblyDescription = "Elasticsearch Type Provider"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
